name: Build Docker Image

on:
  push:
    branches: ['v**']
  pull_request:
    branches: ['v**']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker_Image

    strategy:
      matrix:
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract IMAGE_TAG
        id: get_version
        run: |
          DATE=$(date +'%Y%m%d')
          REVISION=$(echo $GITHUB_SHA | cut -c1-8)
          echo "IMAGE_TAG=${DATE}-${REVISION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            IMAGE_TAG=${{ steps.get_version.outputs.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            calosliu/instock:${{ steps.get_version.outputs.IMAGE_TAG }}
            calosliu/instock:latest
